### PR TITLE
Subhan 7

### PR DESCRIPTION
**Pull request by SubhanRahiman7**
1.	Updated navigation and footer structure in HTML for better semantics.
	•	Enhanced the structure of the navigation and footer elements to improve semantic meaning and accessibility.
2.	Updated navbar styling in CSS for better layout and design.
	•	Made adjustments to the CSS for the navbar to enhance its visual layout and overall design.
3.	Fixed CSS issue causing incorrect styling.
	•	Resolved an issue that led to incorrect styling in the CSS, ensuring proper appearance.
4.	Updated navbar styling in all HTML files to match new CSS.
	•	Applied the updated navbar styling across all HTML files to ensure consistency in design.

        Please review and merge this PR. If everything looks good, kindly add the Hacktoberfest-accepted label to help this 
        contribution count toward Hacktoberfest.

### CODE REVIEW

**Review by R0Y15 — CHANGES_REQUESTED** [review]
Hi @SubhanRahiman7, the updates are good but the body of the about page is covering the full width of the page. please modify it to cover only upto 70-75% of the body. and please try to match the width of the navbar with the other pages.

**Comment by SubhanRahiman7** [comment]
Hi @R0Y15,

Thanks for the feedback! I’ll update the About page to ensure it covers 70-75% of the body and adjust the navbar width to match the other pages. I’ll also resolve the conflicts shortly.

Appreciate your input!

**Comment by R0Y15** [comment]
hi @SubhanRahiman7 any updates on this issue?

**Comment by SubhanRahiman7** [comment]
You can reply like this:

Hi @R0Y15,

Thanks for checking in! I’m currently preparing for my semester exams, so I won’t be able to make the updates right away. I’ll get back to it as soon as I can after the exams.

Appreciate your understanding!

**Comment by SubhanRahiman7** [comment]
@R0Y15 
I’ve resolved the conflicts for now

**Comment by R0Y15** [comment]
> You can reply like this:
> 
> Hi @R0Y15,
> 
> Thanks for checking in! I’m currently preparing for my semester exams, so I won’t be able to make the updates right away. I’ll get back to it as soon as I can after the exams.
> 
> Appreciate your understanding!

Great, Good luck for your exams, I'm merging this PR, hope to see you around after the exams.

**Pull request merged**
