### PR TITLE
Display of Air Quality Index (AQI) and Voice Search Functionality

### PR DESCRIPTION
**Pull request by sidgureja7803**
Changes Introduced:

1- Air Quality Index (AQI) Display:
The application now shows the Air Quality Index (AQI) for the selected or current location.
AQI values are accompanied by appropriate color indicators and health descriptors based on AQI levels:

Good: Green
Moderate: Yellow
Unhealthy: Orange
Hazardous: Red

2- Voice Search Feature:

Added a voice search button that enables users to input the city name via voice, improving accessibility and user experience.
The voice recognition API processes the spoken input and fetches the weather data for the recognized city without the need for manual typing.

Benefits:
Enhanced Usability: Voice search makes it more convenient for users to get weather updates, especially on mobile devices.
Comprehensive Weather Information: Displaying AQI alongside other weather data provides users with vital information about air quality, making the application more informative.

Screenshot 2024-10-22 030225
Screenshot 2024-10-22 030237

### CODE REVIEW

**Comment by sidgureja7803** [comment]
@R0Y15 please add the hacktober fest label as well.

**Review by R0Y15 — CHANGES_REQUESTED** [review]
Hi @sidgureja7803 these updates are amazing however I request you to fix a small bug in the voice search, a "." is added after the text is transcribed which leads to failure in fetching the weather for location. if you can strip down the text such that only the city name is taken into consideration and no other special characters then it'll fix the issue.

**Comment by sidgureja7803** [comment]
> Hi @sidgureja7803 these updates are amazing however I request you to fix a small bug in the voice search, a "." is added after the text is transcribed which leads to failure in fetching the weather for location. if you can strip down the text such that only the city name is taken into consideration and no other special characters then it'll fix the issue.

@R0Y15 , the feature is working well in my local system.
I have tested the voice feature and there is no, "." being displayed on the search bar along with city name.
and the weather of the city is also fetched correctly.
Share a Screenshot so that i can look into it.

**Comment by R0Y15** [comment]
> > Hi @sidgureja7803 these updates are amazing however I request you to fix a small bug in the voice search, a "." is added after the text is transcribed which leads to failure in fetching the weather for location. if you can strip down the text such that only the city name is taken into consideration and no other special characters then it'll fix the issue.
> 
> @R0Y15 , the feature is working well in my local system. I have tested the voice feature and there is no, "." being displayed on the search bar along with city name. and the weather of the city is also fetched correctly. Share a Screenshot so that i can look into it.

Please look into it,
image
image

**Comment by R0Y15** [comment]
@sidgureja7803 please confirm if the issue still exists in your system, else we can move forward merging this PR.

**Comment by sidgureja7803** [comment]
> @sidgureja7803 please confirm if the issue still exists in your system, else we can move forward merging this PR.

i have made some changes in the code
you will not face the issue now.
The voice recognition feature will not hear any special character now, only the letters.
@R0Y15  please, add hacktoberfest label to this PR and then you can merge it.

**Comment by sidgureja7803** [comment]
@R0Y15, why you are not merging this pr ??????
The issue of "." dot appearing was never in my system. Only you were facing it.
Still, i changed the code. And now you have merged someone's PR, my PR has conflicts.
I added styles, for the voice button and there are conflicts in styles.css files
what should i do now ??

**Comment by R0Y15** [comment]
@sidgureja7803 calm down; there's nothing to worry about conflicts. you can always resolve them, and as far as it is about merging PR's, let me decide that, as a contributor, you should be more focused in coordinating & collaborating with other contributors while making your contributions. That's what hacktober teaches us, isn't it?

Anyway, I've reviewed your contribution, and now it meets the requirements.

**Pull request merged**
