### PR TITLE
fix: button styling

### PR DESCRIPTION
**Pull request by AdityaSinha2305**
I have fixed the 'current location' button styling and 'know more' button styling.
Please do check this and if it works fine do merge this under 'hacktoberfest' label.

image

If current location accessing is not working then try to give permission in settings and try to clear the cache once.

### CODE REVIEW

**Comment by R0Y15** [comment]
@AdityaSinha2305 Please resolve the conflicts

**Comment by AdityaSinha2305** [comment]
@R0Y15 Resolved the conflicts, please check now.

**Comment by AdityaSinha2305** [comment]
@R0Y15  As I am reviewing this update is replaced by 'new card update'.
Should I close this pr or update this pr with my updates ?

**Comment by R0Y15** [comment]
ig, since the current update is based on the last PR pushed by you. I don't think so that this PR would make any change to the current deployment. please look for any other potentials.

**Comment by AdityaSinha2305** [comment]
@R0Y15 Last update is done by you which changes the card style. [Major Card Updates](https://github.com/R0Y15/WeatherNow/commit/e74728ffe77e2e2ecd03959b89f93e3abeeb0ee8)

So do I submit this card style with 'Know More' functionality ?

**Comment by AdityaSinha2305** [comment]
@R0Y15 Could you please check this feature?
Should I create a pr for this functionality ?

**Comment by R0Y15** [comment]
Which functionality? as of the latest commit we don't require any know more button as of now. if you're specifying a different topic please correct me.

**Comment by AdityaSinha2305** [comment]
Okay

**Pull request closed without merging**
