### PR TITLE
feat: Sunrise sunset

### PR DESCRIPTION
**Pull request by AdityaSinha2305**
I have added sunrise and sunset feature do check and if everything works fine merge this and add this under hacktoberfest label.

image

### CODE REVIEW

**Comment by R0Y15** [comment]
@AdityaSinha2305 can we work on making the card look little simplistic. I mean the current card looks like a bunch of list items displayed in the center. what if we make it appear in a grid or something, to make the UI more better?

**Comment by AdityaSinha2305** [comment]
Added new functionality of 'Know More' , hope this makes the card look simpler.

image


After clicking 'Know More' button, more weather data will show for the respective city.
image

Please review this pull request and if everything looks fine do merge this one.
Also check pr #85 if that works fine or not now.

**Comment by R0Y15** [comment]
great, this is a good PR

**Comment by AdityaSinha2305** [comment]
@R0Y15 Can you add this under 'gssoc-ext' label as well ?

**Comment by R0Y15** [comment]
Done.

**Pull request merged**
