### PR TITLE
Add new  event

### PR DESCRIPTION
**Pull request by Cstrp**
Now, when the user enters the name of their city and presses enter, the prompt will be executed. I didn't touch the rest of the code. If desired, I can do a small refactoring.

### CODE REVIEW

**Comment by R0Y15** [comment]
> Now, when the user enters the name of their city and presses enter, the prompt will be executed. I didn't touch the rest of the code. If desired, I can do a small refactoring.

What other refactoring you wish to do?

**Comment by Cstrp** [comment]
> > Now, when the user enters the name of their city and presses enter, the prompt will be executed. I didn't touch the rest of the code. If desired, I can do a small refactoring.

> What other refactoring you wish to do?

Maybe split the code into smaller functions, add jsDoc (typing for better documentation). This will help simplify the code and make it more modular, readable. I don't insist :)

**Comment by R0Y15** [comment]
> > > Now, when the user enters the name of their city and presses enter, the prompt will be executed. I didn't touch the rest of the code. If desired, I can do a small refactoring.
> 
> > What other refactoring you wish to do?
> 
> Maybe split the code into smaller functions, add jsDoc (typing for better documentation). This will help simplify the code and make it more modular, readable. I don't insist :)

okay you can proceed

**Comment by Cstrp** [comment]
> привет @Cstrpне забудьте добавить свою карточку пожертвования на страницу «cotribution.html».

okay

**Pull request merged**
