### PR TITLE
Updated button HTML and CSS while enhancing hover effects for smoothe…

### PR DESCRIPTION
**Pull request by TusharGupta-Developer**
### Fix the Go Button #56

**Objective:**
Enhance the button interaction by implementing hover effects that reveal an arrow and hide the text.

**Changes Made:**
- **Button Color**: Updated the background color for improved contrast and visibility.
- **Box Shadow**: Added a subtle box shadow to provide depth and enhance the button's overall appearance.
- **Hover Effects**: 
  - The background color now darkens more smoothly on hover.
  - Enhanced the shadow effect for a more pronounced visual cue.
- **Text Movement**: 
  - The "Go" text slightly moves to the left when hovered, creating a dynamic interaction.
  - The text fades out smoothly to reveal the arrow.
- **Arrow Translation**: 
  - The arrow now translates in position, ensuring it stays adjacent to the text.
- **Transition Timing**: Increased the duration of transitions to 0.4 seconds for a smoother experience.

**Final Result:**
This implementation creates a button that, upon hovering, smoothly fades out the "Go" text, reveals the adjacent arrow, and provides an aesthetically pleasing hover effect with depth and dynamism.

**Verified:**
- Hover over the button to observe the background color change and the smooth transition of the text and arrow.
- Ensure the "Go" text fades out completely while the arrow becomes visible and translates to the correct position.
- Verify that all transitions occur within the specified duration of 0.4 seconds for consistency.

**Screenshot:**
Screenshot (158)
Screenshot (162)
Feel free to provide feedback or request further adjustments!

### CODE REVIEW

**Comment by R0Y15** [comment]
@TusharGupta-Developer Please resolve the conflicts.

**Comment by TusharGupta-Developer** [comment]
Please review the changes, and let me know if you encounter any further conflicts or issues.

**Comment by R0Y15** [comment]
Kudos!

**Comment by R0Y15** [comment]
Please dont forget to star the project, It'll encourage more contributors

**Comment by TusharGupta-Developer** [comment]
Thank you for the prompt review of my pull request! I appreciate your feedback and the opportunity to contribute to the project. Please let me know if there's anything else you need from my end in this issue or if there are any additional areas where I can assist.

**Comment by TusharGupta-Developer** [comment]
> Please dont forget to star the project, It'll encourage more contributors

done it

**Pull request merged**
