### PR TITLE
feat: AQI added

### PR DESCRIPTION
**Pull request by AdityaSinha2305**
Issue #81 solved.
AQI feature added.
Please check and merge it and assign it under hacktoberfest label!

image

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
@R0Y15  Is location is blocked in settings?
Please do check in browser's privacy and security setting under location tab that the location access is given or not to the local host .

**Comment by R0Y15** [comment]
@AdityaSinha2305 sorry for the delay, as per your PR, the card is displayed only when I click for my location and breaks when I manually search for a city.
Only works for "use my location".

**Comment by AdityaSinha2305** [comment]
@R0Y15 I have added AQI details, please check and merge if everthing works fine under 'hacktoberfest' and 'gssoc-ext', 'level1' label.

image

**Comment by R0Y15** [comment]
@AdityaSinha2305 I'm closing this PR since the new updates are not shown. Please raise a separate PR with the latest commits.

**Pull request closed without merging**
