### PR TITLE
feat: use my current location added

### PR DESCRIPTION
**Pull request by AdityaSinha2305**
A new feature is added where current location is used for weather detection.

### CODE REVIEW

**Comment by R0Y15** [comment]
@AdityaSinha2305 the update is great, but there's a small issue. that the graph disappears when we opt for the current location, and the page height also corrupts while waiting for the user to allow location access. Can we fix it?

**Comment by R0Y15** [comment]
@AdityaSinha2305 Awesome, Great work!

**Comment by R0Y15** [comment]
Please don't forget to star the repo, It'll help encourage other contributors

**Comment by AdityaSinha2305** [comment]
@R0Y15 Can you add this under 'gssoc-ext' label as well ?

**Comment by R0Y15** [comment]
done.

**Pull request merged**
