### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by anant-jain01**
1)changed the nav bar
2) made it's position fixed
3)updated the buttons
4) fixed the "go" button

### CODE REVIEW

**Comment by R0Y15** [comment]
Somethings not right.

**Comment by anant-jain01** [comment]
@R0Y15 what do you feel is not right?

**Comment by anant-jain01** [comment]
@R0Y15 the header is sticky to the top of the page which is the case in most websites
the buttons should follow a same theme so the website looks better cause the buttons are in close proximity if they have different colors and styles then the website looks odd.
the go button on hover the go is changed to the arrow with a good transition

**Comment by R0Y15** [comment]
@anant-jain01 its not about the navbar. just to give you a glance I'm attaching the reference images of your version and the current version.
image
- your Version

image
- currently deployed version

the button styling is good but there's an issue with the hero-txt bg, your version is somewhere making the text blend in with the bg. and also the navbar changes are only for the homepage and not for other pages, which is not a good practice. if you can just focus on improving the button, I'm sure we can merge this PR.

Thanks for understanding

**Comment by anant-jain01** [comment]
@R0Y15 I'll then send another pr just for the buttons then.
thank you

**Pull request closed without merging**
