### PR TITLE
Made website responsive for all devices

### PR DESCRIPTION
**Pull request by Avinash-31**

### CODE REVIEW

**Comment by R0Y15** [comment]
@Avinash-31 the changes you made are pretty impressive but unfortunately the search bar doesn't work somehow, please look at it once and let me know if everything's fine from your side.

**Comment by Avinash-31** [comment]
Okay...on it

**Comment by Avinash-31** [comment]
Hey sent the pr with updates have a check

**Review by R0Y15 — APPROVED** [review]

**Comment by R0Y15** [comment]
hey @Avinash-31 don't forget to add your contribution card in the "cotribution.html" page.

**Pull request merged**
