### PR TITLE
Changed the search box text and centered the search box

### PR DESCRIPTION
**Pull request by syedubaid11**

### CODE REVIEW

**Comment by syedubaid11** [comment]
Changed the search box text and centered the search box for a cleaner look
Removed the footer as it was obstructing the search box
Stretched the width of navbar

**Comment by R0Y15** [comment]
> Changed the search box text and centered the search box for a cleaner look Removed the footer as it was obstructing the search box Stretched the width of navbar

removal of the footer is not an ideal approach. If the search box was getting obstructed then could have found another way to achieve a cleaner look.

**Review by R0Y15 — APPROVED** [review]

**Review by R0Y15 — CHANGES_REQUESTED** [review]
removal of contributions done by others is not accepted, additions and enhancements are accepted.

**Comment by syedubaid11** [comment]
> removal of contributions done by others is not accepted, additions and enhancements are accepted.

Sorry for that , will keep in mind for future.

**Pull request closed without merging**
