### PR TITLE
Gradient Bg and Namecard Addition

### PR DESCRIPTION
**Pull request by Bimme2audrey**

### CODE REVIEW

**Review by R0Y15 — CHANGES_REQUESTED** [review]
the gradient works pretty fine and is decent but the hero-text is excluded from the background which makes it a little fuzzy. please look into it

**Comment by Bimme2audrey** [comment]
Noted. 
Meaning, the hero-text should have a background too?

**Comment by R0Y15** [comment]
> Noted. Meaning, the hero-text should have a background too?

yes the hero-text should also be included in the background

**Comment by Bimme2audrey** [comment]
Alright, noted
Thank you

**Comment by Bimme2audrey** [comment]
Please checkout the change made

**Pull request closed without merging**
